VistoriaApp/Controllers/ImovelController.cs
using Microsoft.AspNetCore.Mvc;
using VistoriaApp.Models;
using VistoriaApp.Repository;

namespace VistoriaApp.Controllers
{
    public class ImovelController : Controller
    {
        private readonly IImovelRepositorio _repositorio;
        public ImovelController(IImovelRepositorio repositorio)
        {
            _repositorio = repositorio;
        }

        public IActionResult Index()
        {
            ICollection<ImovelModel> imovel = _repositorio.BuscarTodos();
            return View(imovel);
        }

        public IActionResult CriarEditar(int? id)
        {
            if (id != null && id != 0)
            {
                ImovelModel imovel = _repositorio.BuscarPorId(id.Value);
                return View(imovel);
            }
            return View();
        }

        [HttpPost]
        public IActionResult CriarEditar(ImovelModel imovel)

        {
            if (ModelState.IsValid)
            {
                if (imovel.Id > 0)
                {
                    if (_repositorio.IdExiste(imovel.Id))
                    {
                        _repositorio.Atualizar(imovel);
                        TempData["mensagem"] = MensagemModel.Serializar("Dados atualizados com sucesso!");
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        TempData["mensagem"] = MensagemModel.Serializar("Não foi possivel atualizar os dados!", Enums.TipoMensagem.Erro);
                        return RedirectToAction("Index");
                    }
                }
                else
                {
                    _repositorio.Adicionar(imovel);
                    TempData["mensagem"] = MensagemModel.Serializar("Dados cadastrados com sucesso!");
                    return RedirectToAction("Index");
                }
            }
            return View(imovel);
        }

        public IActionResult ExcluirConfirmacao(int id)
        {
            if (_repositorio.IdExiste(id))
            {
                ImovelModel ImovelDb = _repositorio.BuscarPorId(id);
                return View(ImovelDb);
            }
            TempData["mensagem"] = MensagemModel.Serializar("Imovel não encontrado.", Enums.TipoMensagem.Erro);
            return RedirectToAction("Index");
        }

        public IActionResult Excluir(int id)
        {
            if (_repositorio.IdExiste(id))
            {
                _repositorio.Excluir(id);
                TempData["mensagem"] = MensagemModel.Serializar("Imóvel excluido com sucesso!");
                return RedirectToAction("Index");
            }
            TempData["mensagem"] = MensagemModel.Serializar("Houve um erro na exclusão do imóvel!", Enums.TipoMensagem.Erro);
            return RedirectToAction("Index");
        }
    }
}

VistoriaApp/Controllers/UsuarioController.cs
using Microsoft.AspNetCore.Mvc;
using VistoriaApp.Data;
using VistoriaApp.Models;
using VistoriaApp.Repository;

namespace VistoriaApp.Controllers
{
    public class UsuarioController : Controller
    {
        private readonly IUsuarioRepositorio _repositorio;

        public UsuarioController(IUsuarioRepositorio repositorio)
        {
            _repositorio = repositorio;
        }

        public IActionResult Index()
        {
            ICollection<UsuarioModel> usuario = _repositorio.BuscarTodos();
            return View(usuario);
        }

        public IActionResult CriarEditar(int? id)
        {
            if (id != null && id != 0)
            {
                UsuarioModel usuario = _repositorio.BuscarPorId(id.Value);
                return View(usuario);
            }
            return View();
        }

        [HttpPost]
        public IActionResult CriarEditar(UsuarioModel usuario)
        {
            if (ModelState.IsValid)
            {
                if (usuario.Id > 0)
                {
                    if (_repositorio.IdExiste(usuario.Id))
                    {
                        _repositorio.Atualizar(usuario);
                        TempData["mensagem"] = MensagemModel.Serializar("Usuário atualizado com sucesso!");
                        return RedirectToAction("Index");
                    }

                    TempData["mensagem"] = MensagemModel.Serializar("Não foi possivel atualizar os dados!", Enums.TipoMensagem.Erro);
                    return RedirectToAction("Index");
                }
                else
                {
                    _repositorio.Adicionar(usuario);
                    TempData["mensagem"] = MensagemModel.Serializar("Usuário criado com sucesso!");
                    return RedirectToAction("Index", "Login");
                }
            }
            return View(usuario);
        }

        public IActionResult ExcluirConfirmacao(int id)
        {
            if (_repositorio.IdExiste(id))
            {
                UsuarioModel usuarioDb = _repositorio.BuscarPorId(id);
                return View(usuarioDb);
            }
            TempData["mensagem"] = MensagemModel.Serializar("Usuário não encontrado!", Enums.TipoMensagem.Erro);
            return RedirectToAction("Index");
        }

        public IActionResult Excluir(int id)
        {
            if (_repositorio.IdExiste(id))
            {
                _repositorio.Excluir(id);
                return RedirectToAction("Index");
            }
            TempData["mensagem"] = MensagemModel.Serializar("Usuário não encontrado!", Enums.TipoMensagem.Erro);
            return RedirectToAction("Index");
        }
    }
}

VistoriaApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - VistoriaApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/VistoriaApp.styles.css" asp-append-version="true" />
    <link href="~/lib/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet" />
    <link href="~/lib/bootstrap-icons/font/bootstrap-icons.min.css" rel="stylesheet" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">VistoriaApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Imovel" asp-action="Index">Imóveis</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Vistoriador" asp-action="Index">Vistoriador</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Vistoria" asp-action="Index">Vistoria</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Usuario" asp-action="Index">Usuário</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - VistoriaApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

VistoriaApp/Views/Shared/_Mensagem.cshtml
@if (TempData.ContainsKey("mensagem")) 
{
    var mensagem = MensagemModel.Desserializar(TempData["mensagem"].ToString()); 

    @if (mensagem.Tipo == VistoriaApp.Enums.TipoMensagem.Erro)
    {
        <div class="alert alert-warning mt-3 alert-dismissible fade show" role="alert">
            @mensagem.Texto
            <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
        </div>
    }
    else
    {
        <div class="alert alert-success mt-3 alert-dismissible fade show" role="alert">
            @mensagem.Texto
            <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
        </div>
    }
}