VistoriaApp/Controllers/AmbienteController.cs
using Microsoft.AspNetCore.Mvc;
using System.Security.Cryptography;
using VistoriaApp.Data;
using VistoriaApp.Models;
using VistoriaApp.Repository;

namespace VistoriaApp.Controllers
{
    public class AmbienteController : Controller
    {
        private readonly IAmbienteRepositorio _repositorio;
        public AmbienteController(IAmbienteRepositorio repositorio) 
        {
            _repositorio = repositorio;
        }

        public IActionResult Criar(int vistoriaId)
        {
            return View();
        }

        [HttpPost]
        public IActionResult Criar(AmbienteModel ambiente)
        {           
            if(ModelState.IsValid)
            {
                _repositorio.Adicionar(ambiente);
                return RedirectToAction("Visualizar", "Vistoria", new {vistoriaId = ambiente.VistoriaId});
            }
            return View(ambiente);
        }

        public IActionResult Excluir(int ambienteId, int vistoId)
        {
            if (_repositorio.IdExiste(ambienteId))
            {
                _repositorio.Excluir(ambienteId);
            }
            return RedirectToAction("Visualizar", "Vistoria", new { vistoriaId = vistoId });
        }
    }
}

VistoriaApp/Controllers/VistoriaController.cs
using Microsoft.AspNetCore.Mvc;
using VistoriaApp.Data;
using VistoriaApp.Models;
using VistoriaApp.Repository;

namespace VistoriaApp.Controllers
{
    public class VistoriaController : Controller
    {
        private readonly IVistoriaRepositorio _repositorio;
        public VistoriaController(IVistoriaRepositorio repositorio)
        {
            _repositorio = repositorio;
        }
        public IActionResult Index()
        {
            ICollection<VistoriaModel> vistoria = _repositorio.BuscarTodos();
            return View(vistoria);
        }

        public IActionResult CriarEditar(int? imovelId)
        {
            if (imovelId != null)
            {
                VistoriaModel vistoriaDb = _repositorio.BuscarPorIdImovel(imovelId.Value);

                if (vistoriaDb != null)
                {
                    return View(vistoriaDb);
                }
                return View();
            }
            TempData["mensagem"] = MensagemModel.Serializar("Não foi possivel criar uma nova vistoria!", Enums.TipoMensagem.Erro);
            return RedirectToAction("Index", "Imovel");
        }

        [HttpPost]
        public IActionResult CriarEditar(VistoriaModel vistoria)
        {
            if (ModelState.IsValid)
            {
                VistoriadorModel vistoriadorDb = _repositorio.BuscarPorIdVistoriador(vistoria.VistoriadorId);

                if (vistoriadorDb != null)
                {
                    if (vistoria.Id > 0)
                    {
                        _repositorio.Atualizar(vistoria);

                        return RedirectToAction("Visualizar", new { vistoriaId = vistoria.Id });
                    }

                    _repositorio.Adicionar(vistoria);
                    return RedirectToAction("Visualizar", new { vistoriaId = vistoria.Id });
                }
                ModelState.AddModelError("VistoriadorId", "Código de vistoriador inválido");
                return View(vistoria);
            }
            return View(vistoria);
        }

        public IActionResult Visualizar(int vistoriaId)
        {
            if (_repositorio.IdExiste(vistoriaId))
            {
                ICollection<AmbienteModel> ambiente = _repositorio.BuscarAmbientes(vistoriaId);
                ViewBag.Ambiente = ambiente;

                VistoriaModel vistoriaDb = _repositorio.BuscarPorId(vistoriaId);
                return View(vistoriaDb);
            }
            TempData["mensagem"] = MensagemModel.Serializar("Vistoria não encontrada", Enums.TipoMensagem.Erro);
            return RedirectToAction("Index", "Vistoria");
        }

        public IActionResult ExcluirConfirmacao(int id)
        {
            if (_repositorio.IdExiste(id))
            {
                VistoriaModel vistoriaDb = _repositorio.BuscarPorId(id);
                return View(vistoriaDb);
            }
            TempData["mensagem"] = MensagemModel.Serializar("Vistoria não encontrado", Enums.TipoMensagem.Erro);
            return RedirectToAction("Index", "Vistoria");
        }

        public IActionResult Excluir(int id)
        {
            if (_repositorio.IdExiste(id))
            {
                _repositorio.Excluir(id);
                TempData["mensagem"] = MensagemModel.Serializar("Vistoria excluida com sucesso!");
                return RedirectToAction("Index", "Vistoria");
            }
            TempData["mensagem"] = MensagemModel.Serializar("Não foi possivel excluir a vistoria!", Enums.TipoMensagem.Erro);
            return RedirectToAction("Index", "Vistoriador");
        }
    }
}

VistoriaApp/Views/Vistoria/CriarEditar.cshtml
@model VistoriaModel

@{
    if (Context.Request.RouteValues.ContainsKey("id"))
        ViewBag.Subtitulo = "Alterar dados da vistoria";
    else
        ViewBag.Subtitulo = "Nova vistoria";
}

<h3 class="text-primary">@ViewBag.Subtitulo</h3>
<hr>

<form class="row g-3" asp-action="CriarEditar" method="post">

    <input type="hidden" asp-for="@Model.ImovelId">

    @if (!Context.Request.RouteValues.ContainsKey("id"))
    {
        <div class="col-md-5">
            <label asp-for="VistoriadorId" class="form-label subTitulo">Digite o código do vistoriador</label>
            <input type="text" asp-for="VistoriadorId" class="form-control">
            <span class="text-danger" asp-validation-for="VistoriadorId"></span>
        </div>
    }
    
    <div class="col-md-2">
        <label asp-for="TipoVistoria" class="form-label subTitulo">Tipo</label>
        <select class="form-select" asp-for="TipoVistoria">
            <option selected></option>
            <option value="1">Inicial</option>
            <option value="2">Final</option>
        </select>
    </div>
    <div class="col-md-5">
        <label asp-for="MedidorAgua" class="form-label subTitulo">Informe o medidor de água</label>
        <input type="text" asp-for="MedidorAgua" class="form-control">
    </div>
    <div class="col-md-5">
        <label asp-for="MedidorEnergia" class="form-label subTitulo">Informe o medidor de energia</label>
        <input type="text" asp-for="MedidorEnergia" class="form-control">
    </div>
    <div class="col-md-2">
        <label asp-for="DataVistoria" class="form-label subTitulo">Data da vistoria</label>
        <input type="date" asp-for="DataVistoria" class="form-control">
    </div>

    <div>
        <button class="btn btn-success" type="submit">Salvar</button>
        <a class="btn btn btn-danger" asp-controller="Vistoria" asp-action="Visualizar" >Cancelar</a>
    </div>

</form>

VistoriaApp/Views/Vistoria/ExcluirConfirmacao.cshtml
@model VistoriaModel

@{
    ViewBag.Subtitulo = "Excluir vistoria";
}

<h1 class="text-primary">@ViewBag.Subtitulo</h1>
<hr>
<h4>
    Deseja realmente excluir vistoria<span class="text-danger"> @Model.Imovel.Endereco.EnderecoCompleto </span>
</h4>

        <div class="mt-3">
            <a class="btn btn-success" asp-controller="Vistoria" asp-action="Visualizar" asp-route-vistoriaId="@Model.Id">Não</a>
            <a class="btn btn-danger" asp-action="Excluir" asp-route-id="@Model.Id">Sim</a>
        </div>

VistoriaApp/Views/Vistoria/Index.cshtml
@model IEnumerable<VistoriaModel>

@{
    ViewBag.Subtitulo = "Listagem de Vistorias";
}

<header class="d-flex justify-content-between align-items-center">
    <div>
        <h1 class="text-primary">@ViewBag.Subtitulo</h1>
    </div>
</header>
<hr>

<partial name="_Mensagem"></partial>

@if (Model != null && Model.Count() > 0)
{
    <table class="table table-striped tabela-imovel">
        <thead>
            <tr>
                <th>Vistorias</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var vistoria in Model)
            {
                <tr>
                    <td>
                        <div><span class="subTitulo">Endereço:</span> @vistoria.Imovel.Endereco.EnderecoCompleto</div>
                        @if(vistoria.Imovel.Locatario == null)
                        {
                            <div><spam class="subTitulo">Locatário:</spam> Não informado</div>
                        }
                        else
                        {
                            <div><span class="subTitulo">Locatário:</span> @vistoria.Imovel.Locatario.Nome</div>
                        }
                        <div><span class="subTitulo">Vistoriador:</span> @vistoria.Vistoriador.Nome</div>
                        <div><span class="subTitulo">Data da vistoria:</span> @vistoria.DataVistoria</div>
                        <div><span class="subTitulo">Tipo:</span> @vistoria.TipoVistoria</div>
                    </td>
                    <td class="btnLista">
                        <a asp-action="Visualizar" asp-route-vistoriaId="@vistoria.Id" class="btn btn-sm btn-secondary">Visualizar</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <p>Não há nenhuma imóvel cadastrado.</p>
}

VistoriaApp/Views/Vistoria/Visualizar.cshtml
@model VistoriaModel

@{
    ViewBag.Subtitulo = "Vistoria";
    ICollection<AmbienteModel> ambiente = ViewBag.ambiente;
}

<header class="d-flex justify-content-between align-items-center">
    <div>
        <h1 class="text-primary">@ViewBag.Subtitulo</h1>
    </div>
    <div>
        <a asp-action="CriarEditar" asp-route-imovelId="@Model.ImovelId" asp-route-id="@Model.Id" class="btn btn-sm btn-success"><i class="bi bi-pencil-square" title="Editar vistoria"></i></a>
        <a asp-action="ExcluirConfirmacao" asp-route-id="@Model.Id" class="btn btn-sm btn-danger"><i class="bi bi-trash-fill" title="Excluir vistoria"></i></a>
    </div>
</header>
<hr>

<div class="visuCabecalho">
    <p class="visuEndereco">@Model.Imovel.Endereco.EnderecoCompleto</p>
    <p><span class="subTitulo">Situação:</span> @Model.Imovel.Situacao <span class="subTitulo">Tipo:</span> @Model.Imovel.TipoImovel</p>
    @if (Model.Imovel.Locatario == null)
    {
        <p><span class="subTitulo">Locatário:</span> Não informado</p>
    }
    else
    {
        <p>
            <span class="subTitulo">Locatário</span>@Model.Imovel.Locatario.LocatarioCompleto 
            <span class="subTitulo">Data de entrada:</span> @Model.Imovel.Locatario.DataEntrada 
            <span class="subTitulo">Data de saída:</span> @Model.Imovel.Locatario.DataSaida
        </p>

    }
    <p>
        <span class="subTitulo">Vistoriador:</span> @Model.Vistoriador.Nome Email: @Model.Vistoriador.Email 
        <span class="subTitulo">Data da vistoria:</span> @Model.DataVistoria
    </p>
    <p>
        <span class="subTitulo">Água:</span> @Model.MedidorAgua 
        <span class="subTitulo">Energia:</span> @Model.MedidorEnergia
    </p>
    <div class="btnAddVistoria">
        <a asp-action="Criar" asp-controller="Ambiente" asp-route-vistoriaId="@Model.Id" class="btn btn-warning">Adicionar ambientes</a>
    </div>
</div>

<hr>


    @foreach (var item in ambiente)
    {
    <table class="tbAmbiente table table-striped table-hover">

        <thead>
            <tr>
                <th class="comodo" colspan="4" scope="col">@item.Comodo</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <th class="categoria" scope="row" >Elétrica</th>
                @if (item.ReparoEletrica == true)
                {
                    <td class="reparo"><i class="bi bi-tools"></i></td>
                }
                else
                {
                    <td class ="reparo"><i class="bi bi-check-circle-fill"></i></td>
                }
                <td class="situacao">@item.SituacaoEletrica</td>
                <td class="obsAmbiente">@item.ObsEletrica</td>
            </tr>
            <tr>
                <th class="categoria" scope="row">Esquadrias</th>
                @if (item.ReparoEsquadrias == true)
                {
                    <td class="reparo"><i class="bi bi-tools"></i></td>
                }
                else
                {
                    <td class="reparo"><i class="bi bi-check-circle-fill"></i></td>
                }
                <td class="situacao">@item.SituacaoEsquadrias</td>
                <td class="obsAmbiente">@item.ObsEsquadrias</td>
            </tr>
            <tr>
                <th class="categoria" scope="row">Hidráulica</th>
                @if (item.ReparoHidraulica == true)
                {
                    <td class="reparo"><i class="bi bi-tools"></i></td>
                }
                else
                {
                    <td class="reparo"><i class="bi bi-check-circle-fill"></i></td>
                }
                <td class="situacao">@item.SituacaoHidraulica</td>
                <td class="obsAmbiente">@item.ObsHidraulica</td>
            </tr>
            <tr>
                <th class="categoria" scope="row">Pintura</th>
                @if (item.ReparoPintura == true)
                {
                    <td class="reparo"><i class="bi bi-tools"></i></td>
                }
                else
                {
                    <td class="reparo"><i class="bi bi-check-circle-fill"></i></td>
                }
                <td class="situacao">@item.SituacaoPintura</td>
                <td class="obsAmbiente">@item.ObsPintura</td>
            </tr>
            <tr>
                <th class="categoria" scope="row">Piso</th>
                @if (item.ReparoPiso == true)
                {
                    <td class="reparo"><i class="bi bi-tools"></i></td>
                }
                else
                {
                    <td class="reparo"><i class="bi bi-check-circle-fill"></i></td>
                }
                <td class="situacao">@item.SituacaoPiso</td>
                <td class="obsAmbiente">@item.ObsPiso</td>
            </tr>
            <tr>
                <th class="categoria" scope="row">Teto</th>
                @if (item.ReparoTeto == true)
                {
                    <td class="reparo"><i class="bi bi-tools"></i></td>
                }
                else
                {
                    <td class="reparo"><i class="bi bi-check-circle-fill"></i></td>
                }
                <td class="situacao">@item.SituacaoTeto</td>
                <td class="obsAmbiente">@item.ObsTeto</td>
            </tr>
            <tr>
                <td class="btnExVistoria" colspan="4"><a asp-controller="Ambiente" asp-action="Excluir" asp-route-vistoId="@Model.Id" asp-route-ambienteId="@item.Id" class="btn btn-sm btn-danger"><i class="bi bi-trash-fill" title="Excluir ambiente"></i></a></td>
            </tr>
        </tbody>
    </table>

    }

 