VistoriaApp/Controllers/ImovelController.cs
using Microsoft.AspNetCore.Mvc;
using VistoriaApp.Models;
using VistoriaApp.Repository;

namespace VistoriaApp.Controllers
{
    public class ImovelController : Controller
    {
        private readonly IImovelRepositorio _repositorio;
        public ImovelController(IImovelRepositorio repositorio)
        {
            _repositorio = repositorio;
        }

        public IActionResult Index()
        {
            ICollection<ImovelModel> imovel = _repositorio.BuscarTodos();
            return View(imovel);
        }

        public IActionResult CriarEditar(int? id)
        {
            if (id != null && id != 0)
            {
                ImovelModel imovel = _repositorio.BuscarPorId(id.Value);
                return View(imovel);
            }
            return View();
        }

        [HttpPost]
        public IActionResult CriarEditar(ImovelModel imovel)

        {
            if (ModelState.IsValid)
            {
                if (imovel.Id > 0)
                {
                    if (_repositorio.IdExiste(imovel.Id))
                    {
                        _repositorio.Atualizar(imovel);
                        TempData["mensagem"] = MensagemModel.Serializar("Dados atualizados com sucesso!");
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        TempData["mensagem"] = MensagemModel.Serializar("Não foi possivel atualizar os dados!", Enums.TipoMensagem.Erro);
                        return RedirectToAction("Index");
                    }
                }
                else
                {
                    _repositorio.Adicionar(imovel);
                    TempData["mensagem"] = MensagemModel.Serializar("Dados cadastrados com sucesso!");
                    return RedirectToAction("Index");
                }
            }
            return View(imovel);
        }

        public IActionResult ExcluirConfirmacao(int id)
        {
            if (_repositorio.IdExiste(id))
            {
                ImovelModel ImovelDb = _repositorio.BuscarPorId(id);
                return View(ImovelDb);
            }
            TempData["mensagem"] = MensagemModel.Serializar("Imovel não encontrado.", Enums.TipoMensagem.Erro);
            return RedirectToAction("Index");
        }

        public IActionResult Excluir(int id)
        {
            if (_repositorio.IdExiste(id))
            {
                _repositorio.Excluir(id);
                TempData["mensagem"] = MensagemModel.Serializar("Imóvel excluido com sucesso!");
                return RedirectToAction("Index");
            }
            TempData["mensagem"] = MensagemModel.Serializar("Houve um erro na exclusão do imóvel!", Enums.TipoMensagem.Erro);
            return RedirectToAction("Index");
        }
    }
}

VistoriaApp/Controllers/LocatarioController.cs
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.Design;
using VistoriaApp.Models;
using VistoriaApp.Repository;

namespace VistoriaApp.Controllers
{
    public class LocatarioController : Controller
    {
        private readonly ILocatarioRepositorio _repositorio;

        public LocatarioController(ILocatarioRepositorio repositorio)
        {
            _repositorio = repositorio;
        }

        public IActionResult Index(int imovelId)
        {
            ImovelModel imovel = _repositorio.BuscarPorIdImovel(imovelId);
            LocatarioModel locatario = _repositorio.BuscarPorFK(imovelId);

            ViewBag.imovel = imovel;
            return View(locatario);
        }

        public IActionResult CriarEditar(int? imovelId)
        {
            LocatarioModel locatarioDb =_repositorio.BuscarPorFK(imovelId.Value);

            if (locatarioDb != null)
            {
                return View(locatarioDb);
            }
            return View();
        }


        [HttpPost]
        public IActionResult CriarEditar(LocatarioModel locatario)
        {
            if (ModelState.IsValid)
            {
                if (locatario.Id > 0)
                {
                    if (_repositorio.IdExiste(locatario.ImovelId))
                    {
                        _repositorio.Atualizar(locatario);
                        TempData["mensagem"] = MensagemModel.Serializar("Locatário atualizado com sucesso!");
                        return RedirectToAction("Index", "Imovel");
                    }
                    else
                    {
                        TempData["mensagem"] = MensagemModel.Serializar("Não foi possivel atualizar os dados!", Enums.TipoMensagem.Erro);
                        return RedirectToAction("Index", "Imovel");
                    }
                }
                else
                {
                    _repositorio.Adicionar(locatario);
                    TempData["mensagem"] = MensagemModel.Serializar("Locatário cadastrado com sucesso!");
                    return RedirectToAction("Index", "Imovel");
                }


            }
            return View(locatario);
        }

        public IActionResult ExcluirConfirmacao(int imovelId)
        {
            if (_repositorio.IdExiste(imovelId))
            {
                LocatarioModel locatario = _repositorio.BuscarPorFK(imovelId);
                return View(locatario);
            }
            TempData["mensagem"] = MensagemModel.Serializar("Imovel não encontrado", Enums.TipoMensagem.Erro);
            return RedirectToAction("Index");
        }

        public IActionResult Excluir(int imovelId)
        {
            if (_repositorio.IdExiste(imovelId))
            {
                _repositorio.Excluir(imovelId);
                TempData["mensagem"] = MensagemModel.Serializar("Locatário excluido com sucesso!");
                return RedirectToAction("Index", "Imovel");
            }
            TempData["mensagem"] = MensagemModel.Serializar("Não foi possivel excluir os dados!", Enums.TipoMensagem.Erro);
            return RedirectToAction("Index", "Imovel");
        }
    }
}

VistoriaApp/Views/Imovel/CriarEditar.cshtml
@model ImovelModel

@{
    if (Context.Request.RouteValues.ContainsKey("id")) 
        ViewBag.Subtitulo = "Alteração de dados";
    else
        ViewBag.Subtitulo = "Novo Imovel";
}

<h3 class="text-primary">@ViewBag.Subtitulo</h3>
<hr>

<form class="row g-3" asp-action="CriarEditar" method="post">  
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="col-md-5">
        <label asp-for="Endereco.Rua" class="form-label subTitulo">Rua</label>
        <input type="text" asp-for="Endereco.Rua" class="form-control">
        <span class="text-danger" asp-validation-for="Endereco.Rua"></span>

    </div>
    <div class="col-md-5">
        <label asp-for="Endereco.Bairro" class="form-label subTitulo">Bairro</label>
        <input type="text" asp-for="Endereco.Bairro" class="form-control">
        <span class="text-danger" asp-validation-for="Endereco.Bairro"></span>

    </div>
    <div class="col-md-2">
        <label asp-for="Endereco.Numero" class="form-label subTitulo">Número</label>
        <input type="text" asp-for="Endereco.Numero" class="form-control">
        <span class="text-danger" asp-validation-for="Endereco.Numero"></span>
    </div>
    <div class="col-md-5">
        <label asp-for="Endereco.Cidade" class="form-label subTitulo">Cidade</label>
        <input type="text" asp-for="Endereco.Cidade" class="form-control">
        <span class="text-danger" asp-validation-for="Endereco.Cidade"></span>

    </div>
    <div class="col-md-1">
        <label asp-for="Endereco.UF" class="form-label subTitulo">UF</label>
        <select class="form-select" asp-for="Endereco.UF">
            <option selected></option>
            <option value="AC">AC</option>
            <option value="AL">AL</option>
            <option value="AP">AP</option>
            <option value="AM">AM</option>
            <option value="BA">BA</option>
            <option value="CE">CE</option>
            <option value="DF">DF</option>
            <option value="ES">ES</option>
            <option value="GO">GO</option>
            <option value="MA">MA</option>
            <option value="MT">MT</option>
            <option value="MS">MS</option>
            <option value="MG">MG</option>
            <option value="PA">PA</option>
            <option value="PB">PB</option>
            <option value="PR">PR</option>
            <option value="PE">PE</option>
            <option value="PI">PI</option>
            <option value="RJ">RJ</option>
            <option value="RN">RN</option>
            <option value="RS">RS</option>
            <option value="RO">RO</option>
            <option value="RR">RR</option>
            <option value="SC">SC</option>
            <option value="SP">SP</option>
            <option value="SE">SE</option>
            <option value="TO">TO</option>
        </select>

    </div>
    <div class="col-md-2">
        <label asp-for="Endereco.CEP" class="form-label subTitulo">CEP</label>
        <input type="text" asp-for="Endereco.CEP" class="form-control">
        <span class="text-danger" asp-validation-for="Endereco.CEP"></span>

    </div>
    <div class="col-md-2">
        <label asp-for="TipoImovel" class="form-label subTitulo">Tipo</label>
        <select class="form-select" asp-for="TipoImovel">
            <option selected></option>
            <option value="1">Apartamento</option>
            <option value="2">Casa</option>
            <option value="3">Comercial</option>
        </select>

    </div>
    <div class="col-md-5">
        <label asp-for="Endereco.Complemento" class="form-label subTitulo">Complemento</label>
        <input type="text" asp-for="Endereco.Complemento" class="form-control">
    </div>
    <div class="col-md-2">
        <label asp-for="Situacao" class="form-label subTitulo">Situação</label>
        <select class="form-select" asp-for="Situacao">
            <option selected></option>
            <option value="1">Ocupado</option>
            <option value="2">Desocupado</option>
        </select>

    </div>

    <div>
        <button class="btn btn-success" type="submit">Salvar</button>
        <a class="btn btn btn-danger" asp-controller="Imovel" asp-action="Index">Cancelar</a>
    </div>
</form>

VistoriaApp/Views/Imovel/ExcluirConfirmacao.cshtml
@model ImovelModel

@{
    ViewBag.Subtitulo = "Excluir Imovel";
}

<h1 class="text-primary">@ViewBag.Subtitulo</h1>
<hr>
<h4>
    Deseja realmente excluir Imóvel<span class="text-danger"> @Model.Endereco.Bairro </span>
</h4>

        <div class="mt-3">
            <a class="btn btn-success" asp-controller="Imovel" asp-action="Index">Não</a>
            <a class="btn btn-danger" asp-action="Excluir" asp-route-id="@Model.Id">Sim</a>
        </div>

VistoriaApp/Views/Imovel/Index.cshtml
@model ICollection<ImovelModel>

@{
    ViewBag.Subtitulo = "Listagem de Imóveis";
}

<header class="d-flex justify-content-between align-items-center">
    <div>
        <h1 class="text-primary">@ViewBag.Subtitulo</h1>
    </div>
    <div>
        <a asp-action="CriarEditar" class="btn btn-primary">Novo Imóvel</a>
    </div>
</header>
<hr>

<partial name="_Mensagem"></partial>

@if (Model != null && Model.Count() > 0)
{
    <table class="table table-striped tabela-imovel">
        <thead>
            <tr>
                <th>Imóveis</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var imovel in Model)
            {
                <tr>
                    <td class="tipoImovel">
                        @if (imovel.TipoImovel == VistoriaApp.Enums.TipoImovel.Casa)
                        {
                            <i class="bi bi-house iconTipo"></i>
                        }
                        else if (imovel.TipoImovel == VistoriaApp.Enums.TipoImovel.Apartamento)
                        {
                            <i class="bi bi-building iconTipo"></i>
                        }
                        else if (imovel.TipoImovel == VistoriaApp.Enums.TipoImovel.Comercial)
                        {
                            <i class="bi bi-shop iconTipo"></i>
                        }

                    </td>
                    <td>
                        <div><span class="subTitulo">Endereço:</span> @imovel.Endereco.EnderecoCompleto </div>
                        <div><span class="subTitulo">Complemento:</span> @imovel.Endereco.Complemento </div>
                        <div>
                            @if (imovel.Locatario != null)
                            {
                                <span class="subTitulo">Locatário:</span> @imovel.Locatario.LocatarioCompleto
                            }
                            else
                            {
                                <span>
                                    <span class="subTitulo">Locatário:</span> Não infromado
                                </span>
                            }
                        </div>
                        <div><span class="subTitulo">Situação:</span> @imovel.Situacao</div>
                    </td>
                    <td class="btnLista">
                     
                        @if(imovel.Vistoria == null)
                        {
                            <a asp-action="CriarEditar" asp-controller="Vistoria" asp-route-imovelId="@imovel.Id" class="btn btn-sm btn-warning">Criar Vistoria</a>
                        }
                        else
                        {
                            <a asp-action="Visualizar" asp-controller="Vistoria" asp-route-vistoriaId="@imovel.Vistoria.Id" class="btn btn-sm btn-secondary">Visualizar Vistoria</a>
                        }
                        <a asp-action="Index" asp-controller="Locatario" asp-route-imovelId="@imovel.Id" class="btn btn-sm btn-info">Locatário</a>
                        <a asp-action="CriarEditar" asp-route-id="@imovel.Id" class="btn btn-sm btn-success"><i class="bi bi-pencil-square" title="Editar imóvel"></i></a>
                        <a asp-action="ExcluirConfirmacao" asp-route-id="@imovel.Id" class="btn btn-sm btn-danger"><i class="bi bi-trash-fill" title="Excluir imóvel"></i></a>

                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <p>Não há nenhuma imóvel cadastrado.</p>
}